import { test, expect, type Page } from "@playwright/test";
const runId=Date.now().toString();
const accounts={admin:'uiadmin@nst.edu.ph',teacher:'uiteacher@tr.nst.edu.ph',student:'uistudent@my.nst.edu.ph'};
async function login(page:Page,role:keyof typeof accounts){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(accounts[role]);await page.getByLabel('Password',{exact:true}).fill('Initial-test-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/dashboard/);}
test('real admin publishes General and Department announcements; teacher targets a class; student receives them',async({page})=>{
  await login(page,'admin');
  for(const type of ['general','department']){
    await page.goto('/announcements/create');if(type==='department'){await page.getByRole('button',{name:'Department',exact:true}).click();await page.getByLabel('Department *').selectOption({label:'Senior High School'});}
    await page.getByLabel('Title *').fill(`UI real ${type} update ${runId}`);await page.getByLabel('Content *').fill('This update is saved through the real backend in a temporary local test database.');await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page).toHaveURL(/\/announcements$/);await expect(page.getByRole('heading',{name:`UI real ${type} update ${runId}`,exact:true})).toBeVisible();
  }
  await page.getByTestId('sidebar').getByRole('button',{name:'Log out'}).click();await expect(page).toHaveURL(/login/);await login(page,'teacher');await page.goto('/announcements/create');await page.getByLabel('Title *').fill(`UI real class reminder ${runId}`);await page.getByLabel('Content *').fill('Teacher message for UI STEM 12.');await page.getByRole('checkbox',{name:/UI STEM 12/}).check();await page.getByRole('button',{name:'Publish class announcement'}).click();await expect(page).toHaveURL(/\/announcements$/);
  await page.getByTestId('sidebar').getByRole('button',{name:'Log out'}).click();await expect(page).toHaveURL(/login/);await login(page,'student');await page.goto('/announcements');
  for(const title of [`UI real general update ${runId}`,`UI real department update ${runId}`,`UI real class reminder ${runId}`])await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open details'}).first().click();await expect(page.getByRole('dialog',{name:'Announcement details'})).toBeVisible();await page.keyboard.press('Escape');
});
test('real student upload appears pending, admin approves it, public gallery displays it',async({page})=>{
  await login(page,'student');await page.goto('/gallery/upload');await page.getByLabel('Event name *').fill(`UI real campus photo ${runId}`);await page.getByLabel('Category *').selectOption({label:'UI School events'});await page.getByLabel('School event image').setInputFiles('e2e/fixtures/tiny.jpg');await page.getByRole('button',{name:'Submit for review'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.goto('/gallery/mine');await expect(page.getByText(`UI real campus photo ${runId}`,{exact:true})).toBeVisible();
  await page.getByTestId('sidebar').getByRole('button',{name:'Log out'}).click();await expect(page).toHaveURL(/login/);await login(page,'admin');await page.goto('/admin/moderation');await expect(page.getByText(`UI real campus photo ${runId}`,{exact:true})).toBeVisible();await page.locator('li').filter({hasText:`UI real campus photo ${runId}`}).getByRole('button',{name:'Approve',exact:true}).click();await expect(page.locator('li').filter({hasText:`UI real campus photo ${runId}`})).toHaveCount(0);await page.getByRole('button',{name:'Approved',exact:true}).click();await expect(page.getByText(`UI real campus photo ${runId}`,{exact:true})).toBeVisible();
  await page.getByTestId('sidebar').getByRole('button',{name:'Log out'}).click();await expect(page).toHaveURL(/login/);await page.goto('/gallery');await expect(page.getByText(`UI real campus photo ${runId}`,{exact:true})).toBeVisible();
});
test('real registration for both roles retains department and section assignment',async({page})=>{
  for(const role of ['student','teacher']){await page.goto(`/register?role=${role}`);await page.getByLabel('Full name').fill(`UI Registered ${role}`);await page.getByLabel('Email',{exact:true}).fill(`uiregistered${role}${runId}@${role==='student'?'my':'tr'}.nst.edu.ph`);await page.getByLabel('Department',{exact:true}).selectOption({label:'Senior High School'});if(role==='student')await page.getByLabel('Section',{exact:true}).selectOption({label:'UI STEM 12'});await page.getByLabel('Password',{exact:true}).fill('RegisteredUi123!');await page.getByLabel('Confirm password',{exact:true}).fill('RegisteredUi123!');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('status')).toContainText(/success|created|registered/i);}
});
test('real admin areas load and role authorization redirects students',async({page})=>{
  await login(page,'admin');for(const path of ['/admin/departments','/admin/events','/admin/users','/admin/categories','/admin/audit-logs','/account']){await page.goto(path);await expect(page.locator('main h1')).toBeVisible();await expect(page.locator('main').getByRole('alert')).toHaveCount(0);}
  await page.getByTestId('sidebar').getByRole('button',{name:'Log out'}).click();await expect(page).toHaveURL(/login/);await login(page,'student');await page.goto('/admin/departments');await expect(page).toHaveURL(/dashboard/);
});
test('real password change invalidates the session and accepts the new password',async({page,context})=>{
  await login(page,'teacher');await page.goto('/account');await page.getByLabel('Current password',{exact:true}).fill('Initial-test-password');await page.getByLabel('New password',{exact:true}).fill('NewTeacherUi123!');await page.getByLabel('Confirm new password',{exact:true}).fill('NewTeacherUi123!');await page.getByRole('button',{name:'Change Password',exact:true}).click();await expect(page.getByRole('link',{name:'Sign in again'})).toBeVisible();expect((await context.cookies()).some(c=>c.name==='ns_token')).toBeFalsy();await page.getByRole('link',{name:'Sign in again'}).click();await page.getByLabel('Email',{exact:true}).fill(accounts.teacher);await page.getByLabel('Password',{exact:true}).fill('NewTeacherUi123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/dashboard/);
});
